export const SAMPLE_HOTELS = {
  has_low_availability: 1,
  search_radius: 0.0,
  applied_filters: [],
  base_filters: [
    {
      title: 'Your budget (for 1 night)',
      type: 'multiple_union',
      layout: {
        collapsed_count: 5,
        is_collapsed: 0,
        is_collapsable: 0,
      },
      iconfont: 'pricetag',
      id: 'price_category',
      categories: [
        {
          to: 50,
          id: 'price_category::50',
          style_for_count: 0,
          display_format: '%LOWER% - %UPPER%',
          selected: 0,
          count: 3,
          from: 0,
          name: '€ 0 - € 50 ',
        },
        {
          name: '€ 50 - € 100 ',
          count: 1,
          from: 50,
          display_format: '%LOWER% - %UPPER%',
          selected: 0,
          style_for_count: 0,
          id: 'price_category::100',
          to: 100,
        },
        {
          from: 100,
          count: 1,
          name: '€ 100 - € 150 ',
          selected: 0,
          display_format: '%LOWER% - %UPPER%',
          style_for_count: 0,
          to: 150,
          id: 'price_category::150',
        },
        {
          count: 1,
          from: 150,
          name: '€ 150 - € 200 ',
          display_format: '%LOWER% + ',
          selected: 0,
          style_for_count: 0,
          to: 200,
          id: 'price_category::200',
        },
      ],
      any_text: 'No price range selected',
      is_group: 1,
      irene_resp_id: 'pri',
    },
    {
      irene_resp_id: 'mealplan',
      is_group: 1,
      categories: [
        {
          style_for_count: 0,
          name: 'Breakfast Included',
          count: 2,
          id: 'mealplan::breakfast_included',
          selected: 0,
        },
      ],
      any_text: 'Any meal options',
      type: 'multiple_union',
      title: 'Meals',
      layout: {
        collapsed_count: 5,
        is_collapsed: 0,
        is_collapsable: 0,
      },
      id: 'mealplan',
      iconfont: 'restaurants',
    },
    {
      type: 'multiple_intersection',
      title: 'Room Facilities',
      iconfont: 'bath',
      layout: {
        is_collapsed: 1,
        collapsed_count: 5,
        is_collapsable: 1,
      },
      id: 'room_facility',
      categories: [
        {
          style_for_count: 0,
          name: 'Private bathroom',
          count: 4,
          id: 'room_facility::38',
          selected: 0,
        },
        {
          id: 'room_facility::75',
          selected: 0,
          name: 'Flat-screen TV',
          style_for_count: 0,
          count: 2,
        },
        {
          style_for_count: 0,
          name: 'Air conditioning',
          count: 4,
          id: 'room_facility::11',
          selected: 0,
        },
        {
          count: 1,
          name: 'Coffee/Tea maker',
          style_for_count: 0,
          selected: 0,
          id: 'room_facility::998',
        },
        {
          count: 1,
          style_for_count: 0,
          name: 'View',
          selected: 0,
          id: 'room_facility::81',
        },
        {
          selected: 0,
          id: 'room_facility::86',
          count: 1,
          style_for_count: 0,
          name: 'Electric kettle',
        },
      ],
      any_text: 'No room facilities selected',
      is_group: 1,
      irene_resp_id: 'roomfacility',
    },
    {
      irene_resp_id: 'tdb',
      is_group: 1,
      any_text: 'Select bed type',
      categories: [
        {
          count: 2,
          style_for_count: 0,
          name: '2 single beds',
          selected: 0,
          id: 'twin_double_bed::2',
        },
        {
          id: 'twin_double_bed::3',
          selected: 0,
          style_for_count: 0,
          name: 'Double bed',
          count: 4,
        },
      ],
      iconfont: null,
      layout: {
        is_collapsed: 0,
        collapsed_count: 5,
        is_collapsable: 0,
      },
      id: 'twin_double_bed',
      title: 'Bed Preference',
      type: 'multiple_union',
    },
  ],
  is_beach_ufi: 0,
  total_count_with_filters: 4,
  unfiltered_primary_count: 7,
  extended_count: 0,
  result: [
    {
      cc_required: 1,
      is_no_prepayment_block: 0,
      ufi: -2423210,
      children_not_allowed: null,
      city_in_trans: 'in Dagupan',
      review_score: 6.8,
      price_breakdown: {
        currency: 'PHP',
        sum_excluded_raw: 123.84,
        has_incalculable_charges: 0,
        has_tax_exceptions: 0,
        all_inclusive_price: 1155.84,
        gross_price: '1032.00',
        has_fine_print_charges: 0,
      },
      longitude: 120.339311962882,
      matching_units_configuration: {
        matching_units_common_config: {
          unit_type_id: 9,
          localized_area: null,
        },
      },
      selected_review_topic: null,
      preferred_plus: 0,
      latitude: 16.045139405732,
      is_city_center: 0,
      review_recommendation: '',
      type: 'property_card',
      mobile_discount_percentage: 0,
      currencycode: 'PHP',
      is_smart_deal: 0,
      price_is_final: 0,
      has_free_parking: 1,
      is_wholesaler_candidate: 1,
      class: 2.0,
      min_total_price: 1032,
      distance: '7.48',
      accommodation_type_name: 'Inn',
      address_trans: 'Intramuros District, A.B. Fernandez Avenue, Dagupan City',
      cant_book: null,
      extended: 0,
      review_nr: 34,
      address: 'Intramuros District, A.B. Fernandez Avenue, Dagupan City',
      wishlist_count: 0,
      country_trans: 'Philippines',
      checkin: {
        from: '14:00',
        until: '',
      },
      is_beach_front: 0,
      main_photo_id: 166387504,
      timezone: 'Asia/Manila',
      soldout: 0,
      genius_discount_percentage: 0,
      url: 'https://www.booking.com/hotel/ph/value-star-inn.html',
      hotel_facilities:
        '134,179,485,455,5,22,91,464,107,108,488,487,158,163,55,451,450,457,458,46,96,16,2,462,43,47,145,28,44,484,468,467,109,8,14,459,161,454,305,452,143,449,51',
      updated_checkin: null,
      bwallet: {
        hotel_eligibility: 0,
      },
      id: 'property_card_1523010',
      is_free_cancellable: 0,
      district: '',
      class_is_estimated: 1,
      is_mobile_deal: 0,
      accommodation_type: 218,
      currency_code: 'PHP',
      in_best_district: 0,
      native_ads_cpc: 0.0,
      city: 'Dagupan',
      hotel_name: 'Value Star Inn',
      block_ids: ['152301001_335442471_1_0_0'],
      countrycode: 'ph',
      distance_to_cc: '0.35',
      default_wishlist_name: 'Dagupan',
      main_photo_url:
        'https://cf.bstatic.com/xdata/images/hotel/square60/166387504.jpg?k=0222fe853f79d68587699a2153c4a4f3eeec9153a2720f0528cd8a63410123ff&o=',
      zip: '2400',
      badges: [],
      default_language: 'xu',
      review_score_word: 'Pleasant',
      hotel_has_vb_boost: 0,
      cc1: 'ph',
      district_id: 0,
      is_geo_rate: '',
      checkout: {
        from: '',
        until: '12:00',
      },
      hotel_include_breakfast: 0,
      deals: {
        deal_attributes: {},
        deals_available: {},
        deal_events_killswitch: 0,
      },
      urgency_room_msg: 'Standard Double Room',
      native_ad_id: '',
      hotel_name_trans: 'Value Star Inn',
      preferred: 0,
      native_ads_tracking: '',
      is_genius_deal: 0,
      districts: '',
      city_trans: 'Dagupan',
      urgency_message: 'Only 2 left at this price on Booking.com',
      city_name_en: 'Dagupan',
      hotel_id: 1523010,
      updated_checkout: null,
    },
    {
      distance: '7.42',
      min_total_price: 2665.48,
      accommodation_type_name: 'Hotel',
      price_is_final: 0,
      class: 3.0,
      is_wholesaler_candidate: 1,
      has_free_parking: 1,
      type: 'property_card',
      is_smart_deal: 0,
      mobile_discount_percentage: 296.16,
      currencycode: 'PHP',
      latitude: 16.0448490646138,
      is_city_center: 0,
      preferred_plus: 0,
      review_recommendation: '',
      selected_review_topic: null,
      price_breakdown: {
        has_incalculable_charges: 0,
        sum_excluded_raw: 319.86,
        currency: 'PHP',
        has_fine_print_charges: 0,
        gross_price: 2665.48,
        all_inclusive_price: 2985.34,
        has_tax_exceptions: 0,
      },
      matching_units_configuration: {
        matching_units_common_config: {
          unit_type_id: 9,
          localized_area: null,
        },
      },
      longitude: 120.340201556683,
      review_score: 7.5,
      is_no_prepayment_block: 0,
      cc_required: 1,
      city_in_trans: 'in Dagupan',
      ufi: -2423210,
      children_not_allowed: null,
      updated_checkin: null,
      hotel_facilities:
        '51,117,452,48,305,27,449,160,459,454,161,467,453,44,484,486,461,109,8,6,53,43,47,59,20,16,96,2,462,81,46,451,458,450,457,3,487,488,108,464,107,163,55,5,455,22,134,485,179',
      url: 'https://www.booking.com/hotel/ph/star-plaza.html',
      soldout: 0,
      timezone: 'Asia/Manila',
      genius_discount_percentage: 0,
      main_photo_id: 353643162,
      checkin: {
        from: '14:00',
        until: '',
      },
      country_trans: 'Philippines',
      is_beach_front: 0,
      wishlist_count: 0,
      address: 'A.B. Fernandez Avenue, Pangasinan',
      review_nr: 37,
      address_trans: 'A.B. Fernandez Avenue, Pangasinan',
      cant_book: null,
      extended: 0,
      badges: [
        {
          id: 'combined-discount',
          badge_variant: 'constructive',
          text: '19% off',
        },
      ],
      zip: '2400',
      hotel_has_vb_boost: 0,
      review_score_word: 'Good',
      default_language: 'en',
      main_photo_url:
        'https://cf.bstatic.com/xdata/images/hotel/square60/353643162.jpg?k=ced74da3007bf4c7fbeefb2d4be1b737694ddb47bd455c3d62b328b339aba111&o=',
      distance_to_cc: '0.40',
      default_wishlist_name: 'Dagupan',
      countrycode: 'ph',
      native_ads_cpc: 0.0,
      in_best_district: 0,
      hotel_name: 'Star Plaza Hotel',
      block_ids: ['159298102_335447404_0_1_0'],
      city: 'Dagupan',
      currency_code: 'PHP',
      accommodation_type: 204,
      is_mobile_deal: 1,
      class_is_estimated: 1,
      district: '',
      is_free_cancellable: 0,
      id: 'property_card_1592981',
      bwallet: {
        hotel_eligibility: 0,
      },
      hotel_id: 1592981,
      updated_checkout: null,
      city_trans: 'Dagupan',
      city_name_en: 'Dagupan',
      native_ads_tracking: '',
      preferred: 0,
      districts: '',
      is_genius_deal: 0,
      hotel_name_trans: 'Star Plaza Hotel',
      native_ad_id: '',
      urgency_room_msg: 'Junior Double Room (No Window)',
      deals: {
        deals_available: {},
        deal_events_killswitch: 0,
        deal_attributes: {},
      },
      checkout: {
        until: '12:00',
        from: '',
      },
      hotel_include_breakfast: 1,
      district_id: 0,
      is_geo_rate: '',
      cc1: 'ph',
    },
    {
      is_wholesaler_candidate: 1,
      class: 0.0,
      has_free_parking: 1,
      price_is_final: 1,
      accommodation_type_name: 'Hotel',
      distance: '4.71',
      min_total_price: 5737.5,
      review_recommendation: '',
      latitude: 16.022675,
      is_city_center: 0,
      preferred_plus: 0,
      is_smart_deal: 0,
      mobile_discount_percentage: 637.5,
      currencycode: 'PHP',
      type: 'property_card',
      matching_units_configuration: {
        matching_units_common_config: {
          localized_area: null,
          unit_type_id: 24,
        },
      },
      longitude: 120.358783,
      price_breakdown: {
        currency: 'PHP',
        sum_excluded_raw: '0.00',
        has_incalculable_charges: 0,
        all_inclusive_price: 5737.5,
        has_tax_exceptions: 0,
        has_fine_print_charges: 0,
        gross_price: '5737.50',
      },
      selected_review_topic: null,
      city_in_trans: 'in Calasiao',
      children_not_allowed: null,
      ufi: -2418865,
      is_no_prepayment_block: 0,
      cc_required: 1,
      review_score: 8.7,
      hotel_facilities:
        '28,7,119,47,25,16,420,81,3,451,188,101,163,158,464,91,253,455,176,179,433,485,134,220,110,51,301,23,305,424,48,452,161,186,406,189,184,468,453,467,6,177,20,425,304,419,198,462,2,52,96,78,46,181,457,450,458,107,488,487,11,22,185,203,5,256,221,418,199,73,129,423,124,449,422,454,456,14,459,160,8,461,109,486,205,104,258',
      url: 'https://www.booking.com/hotel/ph/the-monarch.html',
      updated_checkin: null,
      main_photo_id: 215994135,
      soldout: 0,
      timezone: 'Asia/Manila',
      genius_discount_percentage: 0,
      wishlist_count: 0,
      is_beach_front: 0,
      checkin: {
        from: '15:00',
        until: '00:00',
      },
      country_trans: 'Philippines',
      cant_book: null,
      extended: 0,
      address_trans: 'McArthur Highway, Barangay San Miguel, Pangasinan',
      address: 'McArthur Highway, Barangay San Miguel, Pangasinan',
      review_nr: 145,
      main_photo_url:
        'https://cf.bstatic.com/xdata/images/hotel/square60/215994135.jpg?k=0974c4754c97ba8b3238309156638d7c5e84af660fbe31af2a194b19a9dc391a&o=',
      hotel_has_vb_boost: 0,
      review_score_word: 'Excellent',
      default_language: 'xu',
      badges: [
        {
          text: '10% off',
          badge_variant: 'constructive',
          id: 'combined-discount',
        },
      ],
      zip: '2418',
      block_ids: ['437095901_341904384_0_2_0'],
      hotel_name: 'The Monarch Hotel',
      city: 'Calasiao',
      in_best_district: 0,
      native_ads_cpc: 0.0,
      distance_to_cc: '1.20',
      default_wishlist_name: 'Calasiao',
      countrycode: 'ph',
      district: '',
      class_is_estimated: 1,
      accommodation_type: 204,
      currency_code: 'PHP',
      is_mobile_deal: 1,
      bwallet: {
        hotel_eligibility: 0,
      },
      id: 'property_card_4370959',
      is_free_cancellable: 0,
      city_name_en: 'Calasiao',
      urgency_message: 'Only 4 left at this price on Booking.com',
      city_trans: 'Calasiao',
      updated_checkout: null,
      hotel_id: 4370959,
      hotel_name_trans: 'The Monarch Hotel',
      native_ad_id: '',
      districts: '',
      is_genius_deal: 0,
      preferred: 0,
      native_ads_tracking: '',
      hotel_include_breakfast: 0,
      checkout: {
        from: '12:00',
        until: '12:30',
      },
      has_swimming_pool: 1,
      urgency_room_msg: 'Deluxe Double or Twin Room',
      deals: {
        deal_attributes: {},
        deal_events_killswitch: 0,
        deals_available: {},
      },
      cc1: 'ph',
      is_geo_rate: '',
      district_id: 0,
    },
    {
      class_is_estimated: 1,
      district: '',
      accommodation_type: 204,
      currency_code: 'PHP',
      is_mobile_deal: 0,
      bwallet: {
        hotel_eligibility: 0,
      },
      is_free_cancellable: 0,
      id: 'property_card_9179270',
      main_photo_url:
        'https://cf.bstatic.com/xdata/images/hotel/square60/403933987.jpg?k=dca020e7a65fc5981e8513d10bb6ccd6156e70a6bcb7506e6150535a79aea88d&o=',
      hotel_has_vb_boost: 0,
      default_language: 'xu',
      review_score_word: '',
      badges: [
        {
          badge_variant: 'constructive',
          text: '50% off',
          id: 'combined-discount',
        },
        {
          id: 'new_to_booking',
          text: 'New to Booking.com',
          badge_variant: 'accent',
        },
      ],
      zip: '2419',
      block_ids: ['917927001_363351627_2_0_0'],
      hotel_name: 'Golden Empress Hotel Urdaneta Pangasinan',
      city: 'Santa Barbara',
      native_ads_cpc: 0.0,
      in_best_district: 0,
      default_wishlist_name: 'Santa Barbara',
      distance_to_cc: '0.95',
      countrycode: 'ph',
      hotel_include_breakfast: 0,
      checkout: {
        from: '',
        until: '12:00',
      },
      urgency_room_msg: 'Standard Double Room',
      deals: {
        deal_attributes: {},
        deals_available: {
          has_preset: 1,
        },
        deal_events: [
          {
            localized_name: 'Early 2023 Deal',
            name_translation_tag:
              'sales_campaigns_early2023_deals_badge_name_pd',
            bg_color: '#FF8000',
            description_translation_tag:
              'sales_campaigns_early2023_deals_badge_tooltip_pd',
            preset_id: null,
            icon_url: 'https://summer_deal.com',
            discount_percentage: 40,
            text_color: '#FFFFFF',
            disabled: 0,
            code: 123,
            localized_description:
              'You’re getting a reduced rate because this property is offering a discount on stays between January 1 and March 31, 2023.',
            icon_name: 'percentage-circle',
          },
        ],
        deal_events_killswitch: 0,
      },
      cc1: 'ph',
      is_geo_rate: '',
      district_id: 0,
      city_name_en: 'Santa Barbara',
      city_trans: 'Santa Barbara',
      updated_checkout: null,
      hotel_id: 9179270,
      hotel_name_trans: 'Golden Empress Hotel Urdaneta Pangasinan',
      native_ad_id: '',
      districts: '',
      is_genius_deal: 0,
      preferred: 0,
      native_ads_tracking: '',
      matching_units_configuration: {
        matching_units_common_config: {
          unit_type_id: 9,
          localized_area: null,
        },
      },
      longitude: 120.407964105774,
      price_breakdown: {
        gross_price: 770.86,
        has_fine_print_charges: 0,
        has_tax_exceptions: 0,
        all_inclusive_price: 940.45,
        has_incalculable_charges: 0,
        sum_excluded_raw: 169.59,
        currency: 'PHP',
      },
      selected_review_topic: null,
      city_in_trans: 'in Santa Barbara',
      children_not_allowed: null,
      ufi: -2451299,
      is_no_prepayment_block: 0,
      cc_required: 1,
      review_score: null,
      is_wholesaler_candidate: 1,
      class: 1.0,
      price_is_final: 1,
      accommodation_type_name: 'Hotel',
      distance: '5.93',
      min_total_price: 770.86,
      review_recommendation: '',
      is_city_center: 0,
      latitude: 16.0031368917219,
      preferred_plus: 0,
      is_smart_deal: 0,
      mobile_discount_percentage: 0,
      currencycode: 'PHP',
      type: 'property_card',
      wishlist_count: 0,
      is_beach_front: 0,
      checkin: {
        until: '',
        from: '14:00',
      },
      country_trans: 'Philippines',
      extended: 0,
      cant_book: null,
      address_trans: 'Calasiao - Urdaneta Road Ventinilla Highway',
      address: 'Calasiao - Urdaneta Road Ventinilla Highway',
      review_nr: null,
      hotel_facilities:
        '419,418,425,16,462,443,423,440,448,305,421,449,459,456,451,457,450,435,458,422,442,453,487,464,108,158,109,8,470,455,439,465',
      url: 'https://www.booking.com/hotel/ph/golden-empress-urdaneta-pangasinan.html',
      updated_checkin: null,
      main_photo_id: 403933987,
      genius_discount_percentage: 0,
      timezone: 'Asia/Manila',
      soldout: 0,
    },
  ],
  unfiltered_count: 7,
  ranking_version: 5,
  copyright: [],
  count: 4,
  b_max_los_data: {
    is_fullon: 0,
    extended_los: 90,
    default_los: 45,
    experiment: 'long_stays_android_extend_los_2',
    has_extended_los: 1,
    max_allowed_los: 90,
  },
  recommended_filters: [
    {
      generic_id: 'mealplan::breakfast_included',
      name: 'Breakfast Included',
    },
  ],
  sort: [
    {
      id: 'distance',
      name: 'Distance from place of interest',
    },
    {
      id: 'popularity',
      name: 'Popularity',
    },
    {
      id: 'class_descending',
      name: 'Stars (5 to 0)',
    },
    {
      id: 'class_ascending',
      name: 'Stars (0 to 5)',
    },
    {
      name: 'Guest Review Score',
      id: 'review_score',
    },
    {
      id: 'price',
      name: 'Price (low to high)',
    },
  ],
  search_metadata: 'last_x_property_ids=9179270,hotels_cc1=ph',
  room_distribution: [
    {
      children: [],
      adults: '1',
    },
  ],
  sorting: {
    options: [
      {
        identifier: 'distance',
        loading_message: null,
        name: 'Distance from place of interest',
      },
      {
        identifier: 'popularity',
        loading_message: null,
        name: 'Popularity',
      },
      {
        name: 'Stars (5 to 0)',
        loading_message: null,
        identifier: 'class_descending',
      },
      {
        loading_message: null,
        identifier: 'class_ascending',
        name: 'Stars (0 to 5)',
      },
      {
        loading_message: null,
        identifier: 'review_score',
        name: 'Guest Review Score',
      },
      {
        name: 'Price (low to high)',
        loading_message: null,
        identifier: 'price',
      },
    ],
    selected_identifier: 'popularity',
  },
  page_loading_threshold: 10,
  search_id: 'adb178818c1673708095b6f569a6fbd2204:1:101',
  primary_count: 4,
};
